account:
  sip_server: sip.linphone.org
  sip_username: tifo
  sip_password: ""
  sip_password_ha1: 846b52c8563e31b8649afce1eea8cd1e67993182e5d623881948d83d1f77e643
  sip_identity: sip:tifo@sip.linphone.org
  factory_config_path: config/liblinphone_factory.conf
  transport: tcp
  display_name: YoyoPod

network:
  stun_server: stun.linphone.org
  enable_ice: true

audio:
  preferred_codec: opus
  echo_cancellation: true
  mic_gain: 80
  speaker_volume: 80
  playback_device_id: "ALSA: wm8960-soundcard"
  ringer_device_id: "ALSA: wm8960-soundcard"
  capture_device_id: "ALSA: wm8960-soundcard"
  media_device_id: "ALSA: wm8960-soundcard"
  ring_output_device: ""

messaging:
  conference_factory_uri: ""
  file_transfer_server_url: "https://files.linphone.org/lft.php"
  lime_server_url: "https://lime.linphone.org/lime-server/lime-server.php"
  iterate_interval_ms: 20
  message_store_dir: data/messages
  voice_note_store_dir: data/voice_notes
  voice_note_max_duration_seconds: 30
  auto_download_incoming_voice_recordings: true

auto_answer: false
call_timeout: 60
