"""Walk a Typer app and emit a markdown command-reference table."""

from __future__ import annotations

from io import StringIO
from typing import Any

import typer
from click.core import Group


def _walk(typer_app: typer.Typer, prefix: str = "yoyopod") -> list[tuple[str, str]]:
    """Return [(full_path, short_help), ...] for every leaf command."""
    click_app = typer.main.get_command(typer_app)
    out: list[tuple[str, str]] = []
    _walk_click(click_app, prefix, out)
    return out


def _walk_click(click_cmd: Any, prefix: str, out: list[tuple[str, str]]) -> None:
    if isinstance(click_cmd, Group):
        for name, sub in (click_cmd.commands or {}).items():
            _walk_click(sub, f"{prefix} {name}", out)
    else:
        help_text = click_cmd.short_help or click_cmd.help or ""
        out.append((prefix, help_text.strip().split("\n")[0]))


def generate_commands_md(typer_app: typer.Typer) -> str:
    """Emit the full COMMANDS.md string."""
    entries = _walk(typer_app)

    groups: dict[str, list[tuple[str, str]]] = {
        "Top-level shortcuts": [],
        "`yoyopod remote` - dev-machine to Pi via SSH": [],
        "`yoyopod pi` - on the Pi": [],
        "`yoyopod build`": [],
        "`yoyopod release`": [],
        "`yoyopod setup`": [],
        "`yoyopod dev`": [],
    }

    for path, help_text in entries:
        parts = path.split()
        if len(parts) == 2:
            groups["Top-level shortcuts"].append((path, help_text))
        elif parts[1] == "remote":
            groups["`yoyopod remote` - dev-machine to Pi via SSH"].append((path, help_text))
        elif parts[1] == "pi":
            groups["`yoyopod pi` - on the Pi"].append((path, help_text))
        elif parts[1] == "build":
            groups["`yoyopod build`"].append((path, help_text))
        elif parts[1] == "release":
            groups["`yoyopod release`"].append((path, help_text))
        elif parts[1] == "setup":
            groups["`yoyopod setup`"].append((path, help_text))
        elif parts[1] == "dev":
            groups["`yoyopod dev`"].append((path, help_text))

    buf = StringIO()
    buf.write("# YoYoPod CLI - Command Reference\n\n")
    buf.write("Auto-generated by `_docgen.py`. Run `yoyopod dev docs` to regenerate.\n")
    buf.write("For live help, use `yoyopod <cmd> --help`.\n\n")

    for title, cmds in groups.items():
        if not cmds:
            continue
        buf.write(f"## {title}\n\n")
        buf.write("| Command | What it does |\n|---|---|\n")
        for path, help_text in sorted(cmds):
            buf.write(f"| `{path}` | {help_text or '-'} |\n")
        buf.write("\n")

    return buf.getvalue()
