#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Stage {
    CenteredHeroIcon,
    ListWithChrome,
    NowPlayingPanel,
    CallPanel,
    TalkActionsGrid,
    PagedDetail,
    OverlayCenter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RegionId {
    Auto,
    Backdrop,
    Header,
    HeroIcon,
    ListBody,
    ButtonRow,
    Dots,
    Progress,
    Title,
    Subtitle,
    Footer,
    StatusBar,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LayoutRect {
    pub x: i32,
    pub y: i32,
    pub w: i32,
    pub h: i32,
}

pub const fn region_rect(stage: Stage, region: RegionId) -> Option<LayoutRect> {
    match (stage, region) {
        (_, RegionId::Auto) => None,
        (_, RegionId::Backdrop) => Some(LayoutRect {
            x: 0,
            y: 0,
            w: 240,
            h: 280,
        }),
        (_, RegionId::StatusBar) => Some(LayoutRect {
            x: 14,
            y: 10,
            w: 212,
            h: 16,
        }),
        (_, RegionId::Footer) => Some(LayoutRect {
            x: 14,
            y: 244,
            w: 212,
            h: 24,
        }),
        (Stage::CenteredHeroIcon, RegionId::Header) => Some(LayoutRect {
            x: 20,
            y: 38,
            w: 200,
            h: 24,
        }),
        (Stage::CenteredHeroIcon, RegionId::HeroIcon) => Some(LayoutRect {
            x: 62,
            y: 54,
            w: 116,
            h: 116,
        }),
        (Stage::CenteredHeroIcon, RegionId::ListBody) => Some(LayoutRect {
            x: 20,
            y: 176,
            w: 200,
            h: 46,
        }),
        (Stage::CenteredHeroIcon, RegionId::ButtonRow) => Some(LayoutRect {
            x: 64,
            y: 118,
            w: 112,
            h: 42,
        }),
        (Stage::CenteredHeroIcon, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::CenteredHeroIcon, RegionId::Progress) => Some(LayoutRect {
            x: 36,
            y: 202,
            w: 168,
            h: 8,
        }),
        (Stage::CenteredHeroIcon, RegionId::Title) => Some(LayoutRect {
            x: 20,
            y: 176,
            w: 200,
            h: 28,
        }),
        (Stage::CenteredHeroIcon, RegionId::Subtitle) => Some(LayoutRect {
            x: 24,
            y: 204,
            w: 192,
            h: 28,
        }),
        (Stage::ListWithChrome, RegionId::Header) => Some(LayoutRect {
            x: 20,
            y: 42,
            w: 200,
            h: 42,
        }),
        (Stage::ListWithChrome, RegionId::HeroIcon) => Some(LayoutRect {
            x: 16,
            y: 92,
            w: 40,
            h: 40,
        }),
        (Stage::ListWithChrome, RegionId::ListBody) => Some(LayoutRect {
            x: 12,
            y: 86,
            w: 216,
            h: 166,
        }),
        (Stage::ListWithChrome, RegionId::ButtonRow) => Some(LayoutRect {
            x: 16,
            y: 208,
            w: 208,
            h: 32,
        }),
        (Stage::ListWithChrome, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::ListWithChrome, RegionId::Progress) => Some(LayoutRect {
            x: 36,
            y: 202,
            w: 168,
            h: 8,
        }),
        (Stage::ListWithChrome, RegionId::Title) => Some(LayoutRect {
            x: 20,
            y: 42,
            w: 200,
            h: 24,
        }),
        (Stage::ListWithChrome, RegionId::Subtitle) => Some(LayoutRect {
            x: 20,
            y: 66,
            w: 200,
            h: 18,
        }),
        (Stage::NowPlayingPanel, RegionId::Header) => Some(LayoutRect {
            x: 0,
            y: 38,
            w: 240,
            h: 214,
        }),
        (Stage::NowPlayingPanel, RegionId::HeroIcon) => Some(LayoutRect {
            x: 74,
            y: 50,
            w: 92,
            h: 66,
        }),
        (Stage::NowPlayingPanel, RegionId::ListBody) => Some(LayoutRect {
            x: 16,
            y: 134,
            w: 208,
            h: 70,
        }),
        (Stage::NowPlayingPanel, RegionId::ButtonRow) => Some(LayoutRect {
            x: 70,
            y: 208,
            w: 100,
            h: 24,
        }),
        (Stage::NowPlayingPanel, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::NowPlayingPanel, RegionId::Progress) => Some(LayoutRect {
            x: 36,
            y: 240,
            w: 168,
            h: 8,
        }),
        (Stage::NowPlayingPanel, RegionId::Title) => Some(LayoutRect {
            x: 16,
            y: 134,
            w: 208,
            h: 44,
        }),
        (Stage::NowPlayingPanel, RegionId::Subtitle) => Some(LayoutRect {
            x: 16,
            y: 184,
            w: 208,
            h: 16,
        }),
        (Stage::CallPanel, RegionId::Header) => Some(LayoutRect {
            x: 54,
            y: 208,
            w: 132,
            h: 24,
        }),
        (Stage::CallPanel, RegionId::HeroIcon) => Some(LayoutRect {
            x: 58,
            y: 42,
            w: 124,
            h: 124,
        }),
        (Stage::CallPanel, RegionId::ListBody) => Some(LayoutRect {
            x: 30,
            y: 176,
            w: 180,
            h: 56,
        }),
        (Stage::CallPanel, RegionId::ButtonRow) => Some(LayoutRect {
            x: 72,
            y: 232,
            w: 96,
            h: 24,
        }),
        (Stage::CallPanel, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::CallPanel, RegionId::Progress) => Some(LayoutRect {
            x: 54,
            y: 208,
            w: 132,
            h: 24,
        }),
        (Stage::CallPanel, RegionId::Title) => Some(LayoutRect {
            x: 30,
            y: 176,
            w: 180,
            h: 24,
        }),
        (Stage::CallPanel, RegionId::Subtitle) => Some(LayoutRect {
            x: 54,
            y: 208,
            w: 132,
            h: 24,
        }),
        (Stage::TalkActionsGrid, RegionId::Header) => Some(LayoutRect {
            x: 50,
            y: 104,
            w: 140,
            h: 16,
        }),
        (Stage::TalkActionsGrid, RegionId::HeroIcon) => Some(LayoutRect {
            x: 96,
            y: 50,
            w: 48,
            h: 48,
        }),
        (Stage::TalkActionsGrid, RegionId::ListBody) => Some(LayoutRect {
            x: 30,
            y: 198,
            w: 180,
            h: 38,
        }),
        (Stage::TalkActionsGrid, RegionId::ButtonRow) => Some(LayoutRect {
            x: 76,
            y: 126,
            w: 88,
            h: 88,
        }),
        (Stage::TalkActionsGrid, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::TalkActionsGrid, RegionId::Progress) => Some(LayoutRect {
            x: 64,
            y: 118,
            w: 112,
            h: 42,
        }),
        (Stage::TalkActionsGrid, RegionId::Title) => Some(LayoutRect {
            x: 30,
            y: 198,
            w: 180,
            h: 22,
        }),
        (Stage::TalkActionsGrid, RegionId::Subtitle) => Some(LayoutRect {
            x: 30,
            y: 220,
            w: 180,
            h: 16,
        }),
        (Stage::PagedDetail, RegionId::Header) => Some(LayoutRect {
            x: 60,
            y: 98,
            w: 120,
            h: 24,
        }),
        (Stage::PagedDetail, RegionId::HeroIcon) => Some(LayoutRect {
            x: 92,
            y: 42,
            w: 56,
            h: 56,
        }),
        (Stage::PagedDetail, RegionId::ListBody) => Some(LayoutRect {
            x: 16,
            y: 126,
            w: 208,
            h: 84,
        }),
        (Stage::PagedDetail, RegionId::ButtonRow) => Some(LayoutRect {
            x: 16,
            y: 126,
            w: 208,
            h: 84,
        }),
        (Stage::PagedDetail, RegionId::Dots) => Some(LayoutRect {
            x: 118,
            y: 238,
            w: 24,
            h: 8,
        }),
        (Stage::PagedDetail, RegionId::Progress) => Some(LayoutRect {
            x: 36,
            y: 202,
            w: 168,
            h: 8,
        }),
        (Stage::PagedDetail, RegionId::Title) => Some(LayoutRect {
            x: 60,
            y: 98,
            w: 120,
            h: 24,
        }),
        (Stage::PagedDetail, RegionId::Subtitle) => Some(LayoutRect {
            x: 16,
            y: 126,
            w: 208,
            h: 84,
        }),
        (Stage::OverlayCenter, RegionId::Header) => Some(LayoutRect {
            x: 18,
            y: 96,
            w: 204,
            h: 34,
        }),
        (Stage::OverlayCenter, RegionId::HeroIcon) => Some(LayoutRect {
            x: 96,
            y: 116,
            w: 48,
            h: 48,
        }),
        (Stage::OverlayCenter, RegionId::ListBody) => Some(LayoutRect {
            x: 24,
            y: 136,
            w: 192,
            h: 48,
        }),
        (Stage::OverlayCenter, RegionId::ButtonRow) => Some(LayoutRect {
            x: 76,
            y: 198,
            w: 88,
            h: 24,
        }),
        (Stage::OverlayCenter, RegionId::Dots) => Some(LayoutRect {
            x: 94,
            y: 224,
            w: 52,
            h: 8,
        }),
        (Stage::OverlayCenter, RegionId::Progress) => Some(LayoutRect {
            x: 96,
            y: 116,
            w: 48,
            h: 48,
        }),
        (Stage::OverlayCenter, RegionId::Title) => Some(LayoutRect {
            x: 18,
            y: 96,
            w: 204,
            h: 34,
        }),
        (Stage::OverlayCenter, RegionId::Subtitle) => Some(LayoutRect {
            x: 24,
            y: 136,
            w: 192,
            h: 48,
        }),
    }
}
